/**
 * continue-from-agent.ts
 *
 * Reads the translated output files written by sub-agents
 *   <AGENT_DIR>/chunks/chunk_NNN_out.xml
 * and the reverse key map
 *   <AGENT_DIR>/chunks/_keymap.json
 * (which maps HASH keys that the bundle generator sent to the sub-agents
 * back to the original GUIDs that the workflow uses), validates each chunk
 * (correct count, correct GUID keys, all keys present), and merges them into
 * a single `translated.xml` at the standard TEMP_TRANSLATED path so the
 * downstream `4-merge.ts` and `5-export-*.ts` steps work as usual.
 */
import * as fs from 'fs';
import * as path from 'path';
import { escapeXml, parseXMLToMap, parseXMLEntries } from '../../utils/xml-parser';

export interface ContinueFromAgentOptions {
  workflowName: string;
  agentDir: string;
  /** Path to the "expected" XML = new.xml (output of step 2 detect-changes).
   *  Keys here are still original GUIDs. */
  expectedXmlPath: string;
  /** Path where merged translated.xml (GUID-keyed) will be written. */
  translatedXmlPath: string;
}

function listChunkOutputFiles(chunksDir: string): string[] {
  if (!fs.existsSync(chunksDir)) return [];
  return fs
    .readdirSync(chunksDir)
    .filter(f => /^chunk_\d{3}_out\.xml$/.test(f))
    .sort();
}

function loadReverseKeyMap(chunksDir: string): Record<string, string> {
  const keymapFile = path.join(chunksDir, '_keymap.json');
  if (!fs.existsSync(keymapFile)) return {};
  try {
    const raw = fs.readFileSync(keymapFile, 'utf-8');
    const parsed = JSON.parse(raw) as Record<string, string>;
    if (parsed && typeof parsed === 'object') return parsed;
  } catch (err) {
    console.warn(`⚠️  Không parse được _keymap.json, tiếp tục mà không remap key.`);
  }
  return {};
}

/**
 * Top-level entry point used by each per-workflow agent-finish.ts.
 */
export function continueFromAgent(opts: ContinueFromAgentOptions): void {
  const { workflowName, agentDir, expectedXmlPath, translatedXmlPath } = opts;

  console.log(`\n=== [Agent Mode] Continue from agent — ${workflowName} ===`);

  if (!fs.existsSync(agentDir)) {
    console.error(`❌ Không tìm thấy agent bundle: ${agentDir}`);
    console.error(`👉 Hãy chạy npm run <wf>:agent (hoặc tương ứng) trước.`);
    process.exit(1);
  }

  const chunksDir = path.join(agentDir, 'chunks');
  const outFiles = listChunkOutputFiles(chunksDir);

  if (outFiles.length === 0) {
    console.error(`❌ Không có chunk output nào trong ${chunksDir}`);
    console.error(`👉 Mỗi sub-agent phải ghi chunks/chunk_NNN_out.xml. Hãy chạy lại :agent và đợi sub-agent xong.`);
    process.exit(1);
  }

  // Expected = Map<Guid, text> of <Text> entries from new.xml (step 2 output)
  const expected = parseXMLToMap(fs.readFileSync(expectedXmlPath, 'utf-8'));
  const expectedKeys = Array.from(expected.keys());
  console.log(`📋 Expected: ${expectedKeys.length} entries from new.xml`);

  // Hash -> Guid reverse map (created by the bundle generator)
  const reverseKeyMap = loadReverseKeyMap(chunksDir);
  if (Object.keys(reverseKeyMap).length > 0) {
    console.log(`🗝️  Loaded _keymap.json với ${Object.keys(reverseKeyMap).length} hash -> GUID entries`);
  } else if (outFiles.length > 0) {
    // Sub-agents wrote Hash keys but we lost the reverse map → can't reconcile.
    console.error(`❌ Không tìm thấy _keymap.json nhưng CÓ chunk_*_out.xml (sub-agent đã dịch).`);
    console.error(`👉 Mỗi sub-agent viết Key dạng HASH, _keymap.json là cầu nối HASH -> GUID.`);
    console.error(`👉 Chạy lại :agent để sinh bundle mới (kèm _keymap.json), rồi cho sub-agent dịch lại.`);
    process.exit(1);
  }

  let totalTranslated = 0;
  let mismatches = 0;
  const missingKeys: string[] = [];

  let combinedXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<STBLKeyStringList>\n';

  for (const file of outFiles) {
    const content = fs.readFileSync(path.join(chunksDir, file), 'utf-8');
    const entries = parseXMLEntries(content);

    if (entries.length === 0) {
      console.error(`⚠️  ${file}: 0 entries (sub-agent có thể chưa dịch hoặc output rỗng)`);
      mismatches++;
      continue;
    }

    const seen = new Set<string>();
    for (const entry of entries) {
      // Translate HASH -> GUID first, using the keymap generated by the bundle.
      const effectiveKey = reverseKeyMap[entry.key] ?? entry.key;

      if (seen.has(effectiveKey)) {
        console.error(`⚠️  ${file}: duplicate Key "${effectiveKey}"`);
        mismatches++;
      }
      seen.add(effectiveKey);

      if (!expected.has(effectiveKey)) {
        console.error(
          `⚠️  ${file}: Key "${effectiveKey}" (input: "${entry.key}") không có trong expected (sub-agent dịch lệch?)`
        );
        mismatches++;
        continue;
      }

      const original = expected.get(effectiveKey)!;
      // Sanity: must contain the same placeholders/tags as original — we only
      // warn, we don't fail, since formatting is preserve-only.
      const expectedPlaceholders = (original.match(/\{\d+\}|\{[\w]+\}|%[sdf]|<[^>]+>|§./g) || []).length;
      const upperPlaceholders = (entry.text.match(/\{\d+\}|\{[\w]+\}|%[sdf]|<[^>]+>|§./g) || []).length;
      if (expectedPlaceholders !== upperPlaceholders) {
        console.error(
          `⚠️  ${file}: Key "${effectiveKey}" placeholder/tag count mismatch (${expectedPlaceholders} -> ${upperPlaceholders})`
        );
      }

      combinedXml += `  <Text Key="${escapeXml(effectiveKey)}">${escapeXml(entry.text)}</Text>\n`;
      totalTranslated++;
    }

    // Find GUIDs declared in expected but missing from this chunk
    for (const key of expectedKeys) {
      if (!seen.has(key)) {
        missingKeys.push(key);
      }
    }
  }

  combinedXml += '</STBLKeyStringList>';

  if (mismatches > 0) {
    console.error(`\n❌ Có ${mismatches} vấn đề trong chunk output. Xem log phía trên.`);
    console.error(`👉 Fix lại các chunk tương ứng rồi chạy lại :agent-finish.`);
    process.exit(1);
  }

  if (missingKeys.length > 0) {
    console.warn(
      `\n⚠️  Cảnh báo: ${missingKeys.length} Key từ expected không xuất hiện trong các chunk output (xem trên).`
    );
  }

  if (totalTranslated < expectedKeys.length) {
    console.warn(
      `\n⚠️  Chỉ dịch được ${totalTranslated}/${expectedKeys.length} entries. Số còn lại sẽ giữ nguyên tiếng Anh hoặc bị bỏ qua tuỳ theo workflow.`
    );
  }

  fs.mkdirSync(path.dirname(translatedXmlPath), { recursive: true });
  fs.writeFileSync(translatedXmlPath, combinedXml, 'utf-8');
  console.log(`✅ Đã merge ${totalTranslated} entries → ${translatedXmlPath}`);
}
